wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1666614018.970407
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.9.12
      5: 0.13.2
      8:
      - 5
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 100
inputs_pr_iteration:
  desc: null
  value: 10000
iterative:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0001
lr_scheduler:
  desc: null
  value: CosineAnnealingLR
name:
  desc: null
  value: dance_gen
optimizer:
  desc: null
  value: Adam
save_dir:
  desc: null
  value: /home/jon/Documents/dance
save_period:
  desc: null
  value: 10
val_inputs_pr_iteration:
  desc: null
  value: 2000
